version: "3.7"
services:
  upload_service:
    build: ./imagestock-upload
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    networks:
      - 'main'
  conversion_service:
    build: ./imagestock-convert
    command: bundle exec rails s -b 0.0.0.0 -p 3001
    ports:
      - "3001:3001"
    links:
      - upload_service
    networks:
      - 'main'
    depends_on:
      - upload_service
networks:
  main:
    driver: "bridge"

